# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-08 16:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=60)),
                ('category_description', models.TextField()),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Invention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invention_name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('video', models.URLField()),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PP_Core.Category')),
            ],
        ),
        migrations.CreateModel(
            name='InventionDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pledge', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('comments', models.TextField()),
                ('improve', models.TextField()),
                ('hide', models.BooleanField()),
                ('save', models.BooleanField()),
                ('invention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PP_Core.Invention')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Inventor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='invention',
            name='inventor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PP_Core.Inventor'),
        ),
    ]
