# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-08 17:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PP_Core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventiondetail',
            old_name='hide',
            new_name='isHidden',
        ),
        migrations.RenameField(
            model_name='inventiondetail',
            old_name='save',
            new_name='isSaved',
        ),
    ]
