# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 10:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PP_Core', '0002_auto_20161008_1737'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
