# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-12 19:14
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PP_Core', '0005_auto_20161105_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='invention',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
