# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-12 19:27
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PP_Core', '0007_auto_20161112_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invention',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='invention_name', unique_with=('add_date',)),
        ),
    ]
