# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 17:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('royalty_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('improvement_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('funding_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
