# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 18:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PP_Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('royalty_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('improvement_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('funding_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('invention_funded', models.IntegerField()),
                ('inventions_saved', models.IntegerField()),
                ('inventions_hidden', models.IntegerField()),
                ('inventions_viewed', models.IntegerField()),
                ('inventions_not_viewed', models.IntegerField()),
                ('pledges_to_fund', models.IntegerField()),
                ('number_of_picks', models.IntegerField()),
                ('picks_in_production', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='user',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
